import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/reusable/header";
import { getTokenContent } from "../(services)/frontend/get_token";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }: Readonly<{ children: React.ReactNode;}>) {

  const user = getTokenContent();
  const {_id, user_type} = user;

  return (
    <html lang="en">
        <body className={inter.className}>
            <div className="w-full min-h-screen flex flex-col">
                <Header params={{slug: user._id}}/>
                {children}
            </div>
        </body>
    </html>
  );
}