import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/reusable/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
        
        <body className={inter.className}>
            <div className="w-full min-h-screen flex flex-col">
                <Header/>
                {children}
            </div>
        </body>
    </html>
  );
}